---
- hosts: odroids pines rpis vms

  tasks:
  - authorized_key: user=root key="{{ lookup('file', '/Users/markus/.ssh/id_rsa.pub') }}"
  - authorized_key: user=root key="{{ lookup('file', '/Users/markus/.ssh/id_ecdsa.pub') }}"
  - lineinfile: dest=/etc/ssh/sshd_config state=present insertafter="^# Authentication" line="PermitRootLogin yes"
  - ini_file: dest=/etc/pacman.conf
              section=custom
              option=SigLevel
              value="Optional TrustAll"
  - ini_file: dest=/etc/pacman.conf
              section=custom
              option=Server
              value="http://mfelten.de/arch-linux/packages/"
  - pacman: update_cache=yes
  - pacman: pkg=ansible state=latest
  - pacman: pkg=nodejs state=latest
  - pacman: pkg=npm state=latest
  - pacman: pkg=nginx state=latest
  - service: name=nginx state=started
