---
- hosts: all
  remote_user: root

  tasks:
  - authorized_key: user=root key="{{ lookup('file', '/Users/markus/.ssh/id_dsa.pub') }}"
  - pacman: pkg=btrfs-progs state=latest
  - pacman: pkg=ansible state=latest
  - pacman: pkg=nodejs state=latest
  - pacman: pkg=npm state=latest
  - pacman: pkg=nginx state=latest
  - service: name=nginx state=started
