# ansible-galaxy install savagegus.consul
---
- hosts: odroids

  tasks:
  - service: name=consul state=stopped
  - file: dest=/var/consul state=absent
  - group: name=consul
  - user: name=consul comment="consul" group=consul home=/var/consul createhome=yes
  - file: path=/var/consul state=directory mode=0755 owner=consul group=consul
  - file: path=/etc/consul state=directory mode=0755 owner=consul group=consul
  - file: dest=/usr/lib/systemd/system-preset/10-odroid.preset state=touch
  - lineinfile: dest=/usr/lib/systemd/system-preset/10-odroid.preset state=present line="enable consul.service"
  - pacman: pkg=consul state=latest
  - service: name=consul state=started
  - command: consul info
