# ansible-galaxy install savagegus.consul
---
- hosts: odroids rpis pines vms

  tasks:
  - service: name=consul state=stopped
  - copy: src=/Users/markus/build/services/arch-linux-arm/ansible/consul/consul.json dest=/etc/consul.d/consul.json
  - pacman: pkg=consul state=latest
  - service: name=consul state=started
  - command: consul info
