---
- hosts: odroids, pines, vms

  tasks:
  - group: name=donkey
  - user: name=donkey comment="donkey" group=donkey createhome=yes shell=/bin/bash
  - authorized_key: user=donkey key="{{ lookup('file', '/Users/markus/.ssh/id_rsa.pub') }}"
  - service: name=kronos-cluster-node state=started
